name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backend/*"
          target: "/home/ubuntu/hockey_app/"
          rm: true # Remove target directory before copying

      - name: Rebuild and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/hockey_app/backend
            # Write secrets into .env file
            cat > .env <<EOF
            PORT=${{ secrets.PROD_PORT }}
            JWT_SECRET=${{ secrets.PROD_JWT_SECRET }}
            MONGODB_URI=${{ secrets.PROD_DB_URI }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            UPLOADS_DIR=uploads/images

            EOF


            # Give .env file permissions
            chmod 600 .env

            # Cleanly recreate the stack
            docker compose down
            docker compose build --no-cache
            docker compose up -d --remove-orphans
